### ISSUE TITLE
Social Attestation for loan request

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable#12]
**Step 2B: Others can "attest" for the loan (i.e. use Bloom or 3Box-linked Ethereum accounts to support the loan)**

Once Loan Request is created, others can "attest" for the loan through Bloom ID or 3Box linked accounts

### Todos

- [ ] Wireframes for social attestation @onggunhao 
- [ ] Set up Bloom ID attestation

- [ ] @onggunhao Watch [Bloom Workshop](https://www.youtube.com/watch?v=SM3KicBROpw&feature=youtu.be&t=1785) to understand starter kit

**Comment by tspoff** [comment]
Bloom doesn't have user staking implemented - but we can do a simple version.

Users can stake eachother via a simple smart contracts which record this. This data can be included into evalutations of user score, which is calculated off-chain for performance reaons. (All primary data is on chain, all derivative data is calculated off-chain)

**Comment by adibas03** [comment]
This answers my question: https://github.com/onggunhao/enable/issues/17#issuecomment-486425132

**Comment by onggunhao** [comment]
We should KIV this for future versions. Not for our V1
