### ISSUE TITLE
Implement frontend dApp based on Balsamiq wireframes

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable#84]
# High-level outcome
To implement the Balsamiq wireframes and integrate Web3 to make mock calls to the Smart Contracts.

# Deadline
19th June (Wednesday)

# Wireframes and specs
The [Balsamiq Interactive Wireframes](https://bit.ly/enable-draft-4) hold the concept wireframes. It basically consists of 4 pages:

[PDF version of clickable prototype](https://github.com/enabledao/enable/files/3277990/Loan.Crowdfunding.1.pdf)

### 1. Main loan page

[Balsamiq Wireframe of Main Loan Page](https://balsamiq.cloud/shdnvpq/pu2y5ti/r2D74?f=N4IgUiBcAMA0IDkpxAYWfAMlAjPAQhiALJEBaRA0lANqgBOUIOATACwDMIAvrA06wCcAUR58QjSCACCHHGzH8pbVKgBiiiQPzDCvJSEEARfOn1ap0nAA5rmySADsHaEftM2ggKxvzDgGxs7O5SXtZs%2FiEg0I7QZuIOamrGUUbqvglMwqj4LFGm1nqZUjjS0nZ%2BTCxGjgrmAEZMgtaOGvAOzq6ajVLNrSDtTEkpDU0tbRYgaWoZoD2G4wOT2bndY%2F2DUtW1a1Ko%2FgdLHS6zIPP7h5sgw6fnB5FX07dMFw%2FLOXmje%2FdHVTV14nmLEEjjeDiEoi%2BIGBoN%2BylUGihMLB2l0u2hIJRvRM8TmVUxcJkNgqgPxsKuBSKeK2BKupXK6MCgnQdOBkNJUiZLMmKnUjM83PBOipZyYXMJxlM%2FOZhKstmlgqYlIVhPpJOpIGs0hY0lVbPRWp1hN5iI5mu1urpwoNFolOJtRqucvVoqkhstk2VUPdqrKLvOLgUrJE6NQgeNCND4ataKhYegQcmktxrrQ0cmzqjCcJXrN8cT4L9oesNT1IbjJccEb5FdLMZF50rdqltarTuJxbrntQhU7bcmavRLC8ahwhJuPAAutwgA%3D%3D)

![image](https://user-images.githubusercontent.com/518024/59297279-d263c580-8c7f-11e9-9406-85287b97e2c4.png)

**Page purpose:**
This page is similar to Kiva's "loan" page. The purpose is to allow potential lenders to find out more about the loan details, and the borrower.

**Notes:**
- [x] Lend button should be anchored to the bottom of the viewport, so that lenders can lend while viewing any part of the page
- [x] If there are many contributing lenders, we should only show a truncated list of lenders
- [x] If Borrower Profile is too long, should only show a shorter excerpt and allow user to click "more" to expand it

### 2. Loan Offer Step 1 (personal details page)

[Balsamiq Wireframe of Loan Offer Step 1](https://balsamiq.cloud/shdnvpq/pu2y5ti/rECB2?f=N4IgUiBcAMA0IDkpxAYWfAMlAjPAQhiALJEBaRA0lANqgBOUIOATACwDMIAvrA06wCcAUR58QjSCACCHHGzH8pbVKgBiiiQPzDCvJSEEARfOn1ap0nAA5rmySADsHaEftM2ggKxvzDgGxs7O5SXtZs%2FiEg0I7QZuIOamrGUUbqvglMwqj4LFGm1nqZUjjS0nZ%2BTCxGjgrmAEZMgtaOGvAOzq6ajVLNrSDtTEkpDU0tbRYgaWoZoD2G4wOT2bndY%2F2DUtW1a1Ko%2FgdLHS6zIPP7h5sgw6fnB5FX07dMFw%2FLOXmje%2FdHVTV14nmLEEjjeDiEoi%2BIGBoN%2BylUGihMLB2l0u2hIJRvRM8TmVUxcJkNgqgPxsKuBSKeK2BKupXK6MCgnQdOBkNJUiZLMmKnUjM83PBOipZyYXMJxlM%2FOZhKstmlgqYlIVhPpJOpIGs0hY0lVbPRWp1hN5iI5mu1urpwoNFolOJtRqucvVoqkhstk2VUPdqrKLvOLgUrJE6NQgeNCND4ataKhYegQcmktxrrQ0cmzqjCcJXrN8cT4L9oesNT1IbjJccEb5FdLMZF50rdqltarTuJxbrntQhU7bcmavRLC8ahwhJuPAAutwgA%3D%3D)

![image](https://user-images.githubusercontent.com/518024/59297300-dee81e00-8c7f-11e9-9b6d-08f0ed91468e.png)

**Page purpose:**
The "email / name" step is purposefully brought forward, because it captures intent to lend for a loan:
* We can launch this first (i.e. "get notified when we launch!") while still working on the Web3 + contracts, to capture interested lenders pre-launch
* This also helps capture the contact detail of a potential lender as soon as possible - this is helpful since many people might drop off during the Metamask step due to Metamask errors
* Collecting video interview requests early on allows Ines to clear them slowly over the weeks prior to the crowdfunding campaign

- [x] This page may be a modal instead of a full page
- [ ] What are the KYC / AUML requirements?
- [ ] Can we include a note / link to Protonmail, if the lender wants to be anonymous?
- [ ] Where does this write to? (backend through a serverless function?)
- [ ] Do we need a recaptcha to prevent spam?

### 3. Loan Offer Step 2 (amount page)

[Balsamiq Wireframe of Loan Offer page](https://balsamiq.cloud/shdnvpq/pu2y5ti/rDCFD?f=N4IgUiBcAMA0IDkpxAYWfAMlAjPAQhiALJEBaRA0lANqgBOUIOATACwDMIAvrA06wCcAUR58QjSCACCHHGzH8pbVKgBiiiQPzDCvJSEEARfOn1ap0nAA5rmySADsHaEftM2ggKxvzDgGxs7O5SXtZs%2FiEg0I7QZuIOamrGUUbqvglMwqj4LFGm1nqZUjjS0nZ%2BTCxGjgrmAEZMgtaOGvAOzq6ajVLNrSDtTEkpDU0tbRYgaWoZoD2G4wOT2bndY%2F2DUtW1a1Ko%2FgdLHS6zIPP7h5sgw6fnB5FX07dMFw%2FLOXmje%2FdHVTV14nmLEEjjeDiEoi%2BIGBoN%2BylUGihMLB2l0u2hIJRvRM8TmVUxcJkNgqgPxsKuBSKeK2BKupXK6MCgnQdOBkNJUiZLMmKnUjM83PBOipZyYXMJxlM%2FOZhKstmlgqYlIVhPpJOpIGs0hY0lVbPRWp1hN5iI5mu1urpwoNFolOJtRqucvVoqkhstk2VUPdqrKLvOLgUrJE6NQgeNCND4ataKhYegQcmktxrrQ0cmzqjCcJXrN8cT4L9oesNT1IbjJccEb5FdLMZF50rdqltarTuJxbrntQhU7bcmavRLC8ahwhJuPAAutwgA%3D%3D)

![image](https://user-images.githubusercontent.com/518024/59297658-a432b580-8c80-11e9-9052-186829516ff4.png)

**Page Purpose:**
* The lender will specify the amount they want to lend and trigger the Web3 action to transfer funds to the crowdfunding smart contract

**Notes:**
This page has received very little user testing vs. its importance to the process. We need to user test the wireframes!
- [ ] This page may be a modal, not a full page (same as Step 1)
- [ ] User test whether Loan Confirmation should be brought higher in the page (i.e. the "fund with metamask" button)
- [ ] Should we move the simulated returns down?
- [ ] Where should we put the disclaimer?

### 4. My Loan page 

[Balsamiq Wireframe of Loan Offer page](https://balsamiq.cloud/shdnvpq/pu2y5ti/r730D?f=N4IgUiBcAMA0IDkpxAYWfAMlAjPAQhiALJEBaRA0lANqgBOUIOATACwDMIAvrA06wCcAUR58QjSCACCHHGzH8pbVKgBiiiQPzDCvJSEEARfOn1ap0nAA5rmySADsHaEftM2ggKxvzDgGxs7O5SXtZs%2FiEg0I7QZuIOamrGUUbqvglMwqj4LFGm1nqZUjjS0nZ%2BTCxGjgrmAEZMgtaOGvAOzq6ajVLNrSDtTEkpDU0tbRYgaWoZoD2G4wOT2bndY%2F2DUtW1a1Ko%2FgdLHS6zIPP7h5sgw6fnB5FX07dMFw%2FLOXmje%2FdHVTV14nmLEEjjeDiEoi%2BIGBoN%2BylUGihMLB2l0u2hIJRvRM8TmVUxcJkNgqgPxsKuBSKeK2BKupXK6MCgnQdOBkNJUiZLMmKnUjM83PBOipZyYXMJxlM%2FOZhKstmlgqYlIVhPpJOpIGs0hY0lVbPRWp1hN5iI5mu1urpwoNFolOJtRqucvVoqkhstk2VUPdqrKLvOLgUrJE6NQgeNCND4ataKhYegQcmktxrrQ0cmzqjCcJXrN8cT4L9oesNT1IbjJccEb5FdLMZF50rdqltarTuJxbrntQhU7bcmavRLC8ahwhJuPAAutwgA%3D%3D)

![image](https://user-images.githubusercontent.com/518024/59298287-2079c880-8c82-11e9-9c75-8173eca0be02.png)

**Page Purpose:**
* After making a successful loan, the lender should be redirected to a dashboard showing the total amount they have loaned, and the repayment schedule and status
* Longer-term, the lender should be able to visit a "My Loan" to track the status of the loan, repayment status, and withdraw his or her balance to his Eth wallet

**Todos**
- [ ] When the lender's loan is successful and he/she is redirected to the "My Loan" screen, there be a success notification on the "My Loan" page 
- [ ] User Testing of this page is very important! 

# Design Guidelines

## Mobile-first, Desktop responsive
The wireframes have been optimized for mobile as we anticipate most first-time visitors will be hearing of this through Twitter or reddit. However, most Ethereum app interaction happens on desktop through Metamask, so the site should be desktop responsive.

A possible example that balances functionality with simplicity is [Balance](https://balance.io/), an open finance wallet. I have attached 2 screenshots below of how it utilizes container width to be usable on both mobile and desktop. 

![image](https://user-images.githubusercontent.com/518024/59286194-3201a700-8c67-11e9-99da-105378f10d49.png)

# Some Todos:

- [ ] @onggunhao and @urmauur Go through React Typescript docs
- [ ] Initial scaffold of Balsamiq wireframes in Typescript + React
- [ ] Web3 integration (either through Drizzle or plain Web3), @onggunhao to evaluate Drizzle
- [ ] Onboard @urmauur onto project

**Comment by onggunhao** [comment]
Story is broken down into
https://github.com/enabledao/enable-ui/issues/5
https://github.com/enabledao/enable-ui/issues/9
https://github.com/enabledao/enable-ui/issues/6
https://github.com/enabledao/enable-ui/issues/7
https://github.com/enabledao/enable-ui/issues/8
