### ISSUE TITLE
Practice and ensure process to redeem stablecoin works (USDC, Paxos etc)

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable#9]
### Why
- On May 20th, Ines will need to show proof to Cornell that she has $60,000 in the bank
- Assuming that the loan amount is funded, we will need to go through the stablecoin provider's redemption process (e.g. USDC, Paxos) to convert the stablecoin into fiat

### Todos
A lot of this is business-related, and Ines will be driving this

- [ ] Research redemption processes for various stablecoins (Paxos, TrueUSD, GUSD, USDC)
- [ ] Go through process for KYC / AUML to get an account with each of the stablecoins
- [ ] If necessary, contact the stablecoin to let them know we are doing this experiment and ask them for help with redemptions / making sure we can 
- [ ] Can we run an experiment where we buy some Stablecoin on an exchange, and then redeem it to a bank account (to test that the process works?)

### Definition of done
* Ines should be able to redeem stablecoins from her crypto wallet, and get fiat in her / her husband's bank account
* She should have gone through the KYC / AUML and activation process for stablecoins 

### Resources (Stablecoin to Fiat redemption)

**Paxos**
[Paxos' redemption process](https://www.paxos.com/user-guide/)

**USDC**
[USDC Redemption Process](https://support.usdc.circle.com/hc/en-us/articles/360015269692-How-to-redeem-USDC-for-USD)

**TrueUSD**
[TrueUSD Redemption Process](https://blog.trusttoken.com/how-to-purchase-and-redeem-trueusd-a-guide-for-traders-ad8b141a9039)

**GUSD**
[GUSD Redemption Process](https://gemini24.zendesk.com/hc/en-us/articles/360001352466-How-do-I-redeem-my-GUSD-for-fiat-USD-)

**Comment by onggunhao** [comment]
@wimanesti has created a USDC wallet, and we will be doing a test run (sending $1) to help her get used to the process

**Comment by onggunhao** [comment]
Trial 1 USDC sent to @wimanesti 

Txn:
https://etherscan.io/tx/0xa75cbe3632bda94c85f1149767f08a93f14cc6b81df848f381c81c9cd2419631

**Comment by onggunhao** [comment]
@wimanesti Ping! There are 2 open tasks above for you to verify that you can redeem 1 USDC to your US bank account

**Comment by onggunhao** [comment]
@wimanesti Ping! Let's make sure the redemption works, and close this issue by end of next week.

**Comment by wimanesti** [comment]
My husband is able to linked his bank account to Coinbase and managed to redeem 5 dollars. I am now sending the rest of USDC to his coinbase account to be redeemed.

**Comment by onggunhao** [comment]
@wimanesti Cool! Could you verify and check what were the fees charged by Coinbase to redeem the 5 USDC to his bank account?

If I'm not wrong, there is a way to avoid withdrawal fees from Coinbase. See 
https://cryptocurrencyhub.io/use-this-secret-method-to-avoid-paying-coinbase-fees-edb5ed65925?gi=3128fa2d33be

You can close this issue once you've looked into how to withdraw with as little fees as possible.

**Comment by wimanesti** [comment]
Trading ~15.63 ETH (~$4,512.27) to USDC worth 4470.62 (trading fee $50.98)?

**Comment by wimanesti** [comment]
> @wimanesti Cool! Could you verify and check what were the fees charged by Coinbase to redeem the 5 USDC to his bank account?

No fee is charged to to withdraw 100 USDC at Wells Fargo

**Comment by onggunhao** [comment]
@wimanesti No! Just the 5 USDC - were there any fees?

I'm not going to give any advice on whether you should hodl the ETH or convert it to a stablecoin - I'll leave you to research Bitcoin, Ethereum and the "hodl" movement...

Interestingly, it might be interesting to come up with the concept of "undercollateralized" loans - you "staking" the 15 ETH you have as collateral for a 60,000 Dai loan. (cc @tspoff @adibas03)

**Comment by wimanesti** [comment]
> @wimanesti No! Just the 5 USDC - were there any fees?
No fee whatsoever. But it takes 5 days to withdraw

**Comment by onggunhao** [comment]
@wimanesti Please close this issue once you've verified the fees charged for withdrawing to bank account
